### ISSUE TITLE
Add markdown support

### ISSUE THREAD

**Issue by coderhs** [reddotrubyconf/rdrc-cfp-app#40]
Is there a plan to add markdown support to the CFP submission? I would like to help out if there is, It would help structure the submissions better.

**Comment by Drenmi** [comment]
Hi, @coderhs!

I briefly considered markdown support, but in the end opted not to add it for the following reasons:

1. The abstract, as provided by the user, will be displayed on the conference website once the talks are selected. To ensure consistency, we would need to first remove any formatting.

2. We are doing double blind reviews, which means there will be a step where a non-reviewer will go through the talks to remove personal identifiers from the outline. Allowing markdown would likely encourage people to add more such information, e.g. links to their social profile etc.

Based on the feedback from the review board, we might add markdown for next year's submissions, but seeing we already have a significant number of submissions, it won't be added for this round.

🙇

**Comment by coderhs** [comment]
I see. In that case I am closing this issue :+1:
